image: openjdk:21

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - export DULNO_GITLAB_PRIVATE_TOKEN="$DULNO_GITLAB_PRIVATE_TOKEN"

build:
  stage: build
  script:
    - ./gradlew assemble